### ISSUE TITLE
希望大神适配卡卡美女网

### ISSUE THREAD

**Issue by wowotaa** [skofkyo/AutoPager#1]
https://m.kaka234.cc/

**Comment by skofkyo** [comment]
抱歉，這網站我知道，但是我這邊連不上，所以做不了...

**Comment by skofkyo** [comment]
手機端嘗試成功連上，需要翻進去...，PC端我再試試，不然手機沒法寫規則。

**Comment by wowotaa** [comment]
谢谢大神



发送自我的盖乐世



-------- 原始信息 --------
发件人： skofkyo ***@***.***>
日期: 2023/9/24 下午5:05 (GMT+08:00)
收件人： skofkyo/AutoPager ***@***.***>
抄送： wowotaa ***@***.***>, Author ***@***.***>
主题： Re: [skofkyo/AutoPager] 希望大神适配卡卡美女网 (Issue #1)


手C端L成功B上，需要翻M去...，PC端我再，不然手C]法t。

―

**Comment by skofkyo** [comment]
規則寫好了，你可以修改腳本加進去。

<pre>
    {
        name: "卡卡美女网 www.kaka234.cc m.kaka234.cc",
        reg: /https?:\/\/(www|m)\.kaka234\.cc\/HTM\/pic\/\w+\/\d+\/\d+\/\d+\.html/i,
        imgs: () => {
            let max;
            try {
                max = fun.geT(".dede_pages li>a,.article_page li>a").match(/\d+/)[0];
            } catch (e) {
                max = 1
            }
            return fun.getImg(".content img,.ArticleImageBox img", max, 9);
        },
        insertImg: ["//div[@class='content'] | //div[div[@class='ArticleImageBox']]", 2],
        autoDownload: [0],
        next: () => {
            let next = fun.ge("//li[contains(text(),'上一篇')]/a");
            if (next) {
                return next.href
            } else {
                return null
            }
        },
        prev: 1,
        customTitle: () => {
            return fun.geT(".Title>h1,.PsBox");
        },
        css: ".m_adv{display:none!important}",
        category: "nsfw1"
    }
</pre>

腳本還有其他紀錄的細節要修改，腳本會過段時間再更新。

**Comment by wowotaa** [comment]
真的太感谢了



发送自我的盖乐世



-------- 原始信息 --------
发件人： skofkyo ***@***.***>
日期: 2023/9/24 下午6:32 (GMT+08:00)
收件人： skofkyo/AutoPager ***@***.***>
抄送： wowotaa ***@***.***>, Author ***@***.***>
主题： Re: [skofkyo/AutoPager] 希望大神适配卡卡美女网 (Issue #1)


t好了，你可以修改_本加M去。

    {
        name: "卡卡美女网 www.kaka234.cc m.kaka234.cc",
        reg: /https?:\/\/(www|m)\.kaka234\.cc\/HTM\/pic\/\w+\/\d+\/\d+\/\d+\.html/i,
        imgs: () => {
            let max;
            try {
                max = fun.geT(".dede_pages li>a,.article_page li>a").match(/\d+/)[0];
            } catch (e) {
                max = 1
            }
            return fun.getImg(".content img,.ArticleImageBox img", max, 9);
        },
        insertImg: ***@***.***='content'] | ***@***.***='ArticleImageBox']]", 2],
        autoDownload: [0],
        next: () => {
            let next = fun.ge("//li[contains(text(),'上一篇')]/a");
            if (next) {
                return next.href
            } else {
                return null
            }
        },
        prev: 1,
        customTitle: () => {
            return fun.geT(".Title>h1,.PsBox");
        },
        css: ".m_adv{display:none!important}",
        category: "nsfw1"
    }


_本有其他o的要修改，_本^段rg再更新。

―
