### ISSUE TITLE
被移动屏蔽了依赖库网址cdn.jsdelivr.net，只能修改后安装了

### ISSUE THREAD

**Issue by bigf8** [skofkyo/AutoPager#2]
有同样情况的可以notepad编辑替换依赖为下面的备用网址：

// @require            https://gcore.jsdelivr.net/npm/jszip@3.9.1/dist/jszip.min.js
// @require            https://gcore.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
// @require            https://fastly.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js

**Comment by skofkyo** [comment]
这种的问题只能用户自己解决了

**Comment by skofkyo** [comment]
依赖库被屏蔽，可以自己修改脚本替换成cdn.bootcdn.net试试看
<pre>
// @require            https://cdn.jsdelivr.net/npm/jszip@3.9.1/dist/jszip.min.js
// @require            https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
// @require            https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js
// @require            https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
</pre>
<pre>
// @require            https://cdn.bootcdn.net/ajax/libs/jszip/3.9.1/jszip.min.js
// @require            https://cdn.bootcdn.net/ajax/libs/jquery/3.7.1/jquery.min.js
// @require            https://cdn.bootcdn.net/ajax/libs/html2canvas/1.4.1/html2canvas.min.js
// @require            https://cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
https://cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
</pre>
