### ISSUE TITLE
网站解析支持

### ISSUE THREAD

**Issue by 9E307** [skofkyo/AutoPager#4]
请对 https://7aipai.com/ 这个网站支持解析。这里面的很好看。

**Comment by skofkyo** [comment]
1.6.0已更新，请试用看看行不行。

**Comment by skofkyo** [comment]
1.6.3修改成是未调整图片宽度的大图链结，保留视频。

**Comment by 9E307** [comment]
目前体验下来完全没问题，感谢作者
