### ISSUE TITLE
FireFox暴力猴，使用插件时出现报错，麻烦看下？

### ISSUE THREAD

**Issue by hobby1999** [skofkyo/AutoPager#5]
无任何改动
浏览器:FireFox 
出现以下报错
![图片](https://github.com/skofkyo/AutoPager/assets/20478009/642cb2d1-3b50-413a-9c35-b4a867eff2a1)

**Comment by skofkyo** [comment]
引入fancybox.umd.js就会报错
删除
<pre>
// @require            https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0.24/dist/fancybox/fancybox.umd.js
</pre>
或改用Fancybox3.5.7
<pre>
// @require            https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
</pre>
就不会报错了，但是FancyboxV5会无法使用，所以这算是暴力猴不支持FancyboxV5的问题？

脚本的主架构是纯JavaScript编写的，只有Fancybox是需要jQuery，压缩则需要JSZip。

想解决需要改成往网页里直接注入依赖库，升级FancyboxV5这个我尝试过，但一部份网站会被拒绝注入，像4KHD就不能直接注入，需要在沙盒里运行才行，取舍下除非必要不然我不会选择直接注入。

脚本1.6.0+以下测试环境是正常的
FireFox 119.0 + Tampermonkey 4.19.0
Cent Browser  5.0.1002.354 + Tampermonkey 4.19.0
Chrome 119.0.6045.106 + Tampermonkey 4.19.0
Edge 119.0.2151.44 + Tampermonkey 4.19.0

你可以选择降低版本至1.5.6，或放弃暴力猴改用Tampermonkey。

**Comment by skofkyo** [comment]
1.6.3之后的版本
<pre>
// @require            https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0.24/dist/fancybox/fancybox.umd.js
</pre>
改成
<pre>
// @require            https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
</pre>
<p>暴力猴应该就能正常使用了</p>

**Comment by hobby1999** [comment]
感谢！
