### ISSUE TITLE
Add new site support

### ISSUE THREAD

**Issue by HaruSasaki** [skofkyo/AutoPager#8]
I'm usually using this site, and want to know if you would add support to it.

The site url is:
https://ahottie.net

The site is look like yase.pics and setushe.pics that have been supported with you script. So I thought is easy to add it.

**Comment by skofkyo** [comment]
Update 2.8.6

**Comment by HaruSasaki** [comment]
That's work perfectly. Thanks for your fast response. Keep doing great job 😄👍
